[workspace]
resolver = "2"
members = [
    "crates/starpls",
    "crates/starpls_bazel",
    "crates/starpls_common",
    "crates/starpls_hir",
    "crates/starpls_ide",
    "crates/starpls_intern",
    "crates/starpls_syntax",
    "crates/starpls_test_util",
    "vendor/runfiles",
]

[workspace.dependencies]
ruff_python_ast = "=0.0.14"
ruff_python_parser = "=0.0.14"
ruff_text_size = "=0.0.14"
ruff_source_file = "=0.0.14"
stacker = "0.1.25"
