[workspace]
resolver = "2"
members = [
    "crates/starpls",
    "crates/starpls_bazel",
    "crates/starpls_common",
    "crates/starpls_hir",
    "crates/starpls_ide",
    "crates/starpls_intern",
    "crates/starpls_syntax",
    "crates/starpls_test_util",
]

[workspace.dependencies]
ruff_python_ast = { git = "https://github.com/tamird/ruff.git", rev = "c27242be93ca448438e5bce2d685a77ce7b0d7c9" }
ruff_python_parser = { git = "https://github.com/tamird/ruff.git", rev = "c27242be93ca448438e5bce2d685a77ce7b0d7c9" }
ruff_text_size = { git = "https://github.com/tamird/ruff.git", rev = "c27242be93ca448438e5bce2d685a77ce7b0d7c9" }
ruff_source_file = { git = "https://github.com/tamird/ruff.git", rev = "c27242be93ca448438e5bce2d685a77ce7b0d7c9" }
stacker = "0.1.25"
salsa = { version = "=0.28.2", default-features = false, features = ["macros", "inventory", "accumulator"] }
ruff_db = { git = "https://github.com/tamird/ruff.git", rev = "c27242be93ca448438e5bce2d685a77ce7b0d7c9", features = ["os"] }
ruff_notebook = { git = "https://github.com/tamird/ruff.git", rev = "c27242be93ca448438e5bce2d685a77ce7b0d7c9" }
