exports_files([
    "LICENSE-MIT",
    "MODULE.bazel",
    "README.md",
    "builder.bzli",
    "frontend.bzli",
    "private_helpers.bzli",
    "providers.bzli",
    "select.bzli",
    "setting.bzli",
    "stubs.toml",
    "transition.bzli",
    "types.bzli",
    "utils.bzli",
    "with_cfg.bzli",
])
