format-version = 1

[source]
repository = "@with_cfg.bzl"
module = "with_cfg.bzl"
versions = ["0.14.6"]

[files]
"with_cfg.bzl" = "with_cfg.bzli"
"with_cfg/private/builder.bzl" = "builder.bzli"
"with_cfg/private/extend.bzl" = "extend.bzli"
"with_cfg/private/frontend.bzl" = "frontend.bzli"
"with_cfg/private/providers.bzl" = "providers.bzli"
"with_cfg/private/select.bzl" = "select.bzli"
"with_cfg/private/setting.bzl" = "setting.bzli"
"with_cfg/private/transition.bzl" = "transition.bzli"
"with_cfg/private/utils.bzl" = "utils.bzli"
"with_cfg/private/with_cfg.bzl" = "private_helpers.bzli"
