[package]
name = "starpls_hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruff_python_ast = { workspace = true }
ruff_text_size = { workspace = true }
stacker = { workspace = true }
ruff_db = { workspace = true }
salsa = { workspace = true }
starpls_bazel = { path = "../starpls_bazel" }
starpls_common = { path = "../starpls_common" }
starpls_syntax = { path = "../starpls_syntax" }
starpls_test_util = { path = "../starpls_test_util" }
rustc-hash = "1.1.0"
anyhow = "1.0.81"
