[package]
name = "starpls_hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ty_flow = { git = "https://github.com/tamird/ruff.git", rev = "cbff046555e11add566bc35a3b29ef8ecf8ebdb0" }
dashmap = "5.5.3"
id-arena = "2.2.1"
salsa = { workspace = true }
starpls_bazel = { path = "../starpls_bazel" }
starpls_common = { path = "../starpls_common" }
starpls_intern = { path = "../starpls_intern" }
starpls_syntax = { path = "../starpls_syntax" }
starpls_test_util = { path = "../starpls_test_util" }
rustc-hash = "1.1.0"
smol_str = "0.2.0"
smallvec = "1.11.2"
either = "1.10.0"
anyhow = "1.0.81"

[dev-dependencies]
expect-test = "1.4.1"
itertools = "0.12.1"
