# Canonical read-only interfaces with supported Starlark mapping methods.
# Python-only mixins and collection views are omitted.
# Generic bases retain the nominal collection constraints used by Ty inference.

class Sequence(Generic[_T_co]):
    @type_check_only
    def __len__(self) -> int: ...
    @type_check_only
    def __iter__(self) -> Iterator[_T_co]: ...
    @type_check_only
    def __reversed__(self) -> Iterator[_T_co]: ...
    @type_check_only
    def __contains__(self, value: object, /) -> bool: ...
    @overload
    @type_check_only
    def __getitem__(self, index: int, /) -> _T_co: ...
    @overload
    @type_check_only
    def __getitem__(self, index: slice, /) -> Sequence[_T_co]: ...

class Mapping(Generic[_KT, _VT_co]):
    @type_check_only
    def __len__(self) -> int: ...
    @type_check_only
    def __iter__(self) -> Iterator[_KT]: ...
    @type_check_only
    def __contains__(self, key: object, /) -> bool: ...
    @type_check_only
    def __getitem__(self, key: _KT, /) -> _VT_co: ...
    @overload
    def get(self, key: object, /, default: None = None) -> _VT_co | None: ...
    @overload
    def get(self, key: object, /, default: _T) -> _VT_co | _T: ...
    def keys(self) -> list[_KT]: ...
    # Sequence preserves value covariance; dict retains its fresh-list results.
    def items(self) -> Sequence[tuple[_KT, _VT_co]]: ...
    def values(self) -> Sequence[_VT_co]: ...

class AbstractSet(Generic[_T_co]):
    @type_check_only
    def __len__(self) -> int: ...
    @type_check_only
    def __iter__(self) -> Iterator[_T_co]: ...
    @type_check_only
    def __contains__(self, value: object, /) -> bool: ...
