# Canonical read-only interfaces. Public Python mixins are not Starlark methods.
# Generic bases retain the nominal collection constraints used by Ty inference.

class Sequence(Generic[_T_co]):
    @type_check_only
    def __len__(self) -> int: ...
    @type_check_only
    def __iter__(self) -> Iterator[_T_co]: ...
    @type_check_only
    def __reversed__(self) -> Iterator[_T_co]: ...
    @type_check_only
    def __contains__(self, value: object, /) -> bool: ...
    @overload
    @type_check_only
    def __getitem__(self, index: int, /) -> _T_co: ...
    @overload
    @type_check_only
    def __getitem__(self, index: slice, /) -> Sequence[_T_co]: ...

class Mapping(Generic[_KT, _VT_co]):
    @type_check_only
    def __len__(self) -> int: ...
    @type_check_only
    def __iter__(self) -> Iterator[_KT]: ...
    @type_check_only
    def __contains__(self, key: object, /) -> bool: ...
    @type_check_only
    def __getitem__(self, key: _KT, /) -> _VT_co: ...
