[package]
name = "starpls_syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drop_bomb = "0.1.5"
rowan = "0.15.11"
ruff_python_parser = { workspace = true }
ruff_python_ast = { workspace = true }
ruff_text_size = { workspace = true }
stacker = { workspace = true }

[build-dependencies]
cc = "*"

[dev-dependencies]
runfiles = { git = "https://github.com/hermeticbuild/rules_rust.git", rev = "00f8db0ed456a59c5bf0643692cc5b30e564018e" }
expect-test = "1.4.1"
