[package]
name = "starpls_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ruff_source_file = { workspace = true }
anyhow = "1.0.81"
salsa = { workspace = true }
starpls_bazel = { path = "../starpls_bazel" }
starpls_syntax = { path = "../starpls_syntax" }
